
using ERCAJ_BANCO_proj.HelperComponents;

namespace ERCAJ_BANCO_proj.Pages
{
	public class ERCAJ_BANCO_Funciones
	{
		//Metodos y atributos de _ERCAJ_BANCO.CAJ_BANCO.SYSUDN_CODIGO_K
public ERCAJ_BANCO_CAJ_BANCO_SYSUDN_CODIGO_K_Componente ERCAJ_BANCO_CAJ_BANCO_SYSUDN_CODIGO_K_Componente;
public void ERCAJ_BANCO_CAJ_BANCO_SYSUDN_CODIGO_K_OnChange()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_SYSUDN_CODIGO_K_OnFocus()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_SYSUDN_CODIGO_K_OnBlur()
{
}
//Metodos y atributos de _ERCAJ_BANCO.CAJ_BANCO.SYSTRA_CODIGO_K
public ERCAJ_BANCO_CAJ_BANCO_SYSTRA_CODIGO_K_Componente ERCAJ_BANCO_CAJ_BANCO_SYSTRA_CODIGO_K_Componente;
public void ERCAJ_BANCO_CAJ_BANCO_SYSTRA_CODIGO_K_OnChange()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_SYSTRA_CODIGO_K_OnFocus()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_SYSTRA_CODIGO_K_OnBlur()
{
}
//Metodos y atributos de _ERCAJ_BANCO.CAJ_BANCO.CAJBAN_SERIE_K
public ERCAJ_BANCO_CAJ_BANCO_CAJBAN_SERIE_K_Componente ERCAJ_BANCO_CAJ_BANCO_CAJBAN_SERIE_K_Componente;
public void ERCAJ_BANCO_CAJ_BANCO_CAJBAN_SERIE_K_OnChange()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_CAJBAN_SERIE_K_OnFocus()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_CAJBAN_SERIE_K_OnBlur()
{
}
//Metodos y atributos de _ERCAJ_BANCO.CAJ_BANCO.CAJBAN_REFERENCIA
public ERCAJ_BANCO_CAJ_BANCO_CAJBAN_REFERENCIA_Componente ERCAJ_BANCO_CAJ_BANCO_CAJBAN_REFERENCIA_Componente;
public void ERCAJ_BANCO_CAJ_BANCO_CAJBAN_REFERENCIA_OnChange()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_CAJBAN_REFERENCIA_OnFocus()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_CAJBAN_REFERENCIA_OnBlur()
{
}
//Metodos y atributos de _ERCAJ_BANCO.CAJ_BANCO.CAJBAN_BANCOREF
public ERCAJ_BANCO_CAJ_BANCO_CAJBAN_BANCOREF_Componente ERCAJ_BANCO_CAJ_BANCO_CAJBAN_BANCOREF_Componente;
public void ERCAJ_BANCO_CAJ_BANCO_CAJBAN_BANCOREF_OnChange()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_CAJBAN_BANCOREF_OnFocus()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_CAJBAN_BANCOREF_OnBlur()
{
}
//Metodos y atributos de _ERCAJ_BANCO.CAJ_BANCO.CONPOL_REFERENCIA
public ERCAJ_BANCO_CAJ_BANCO_CONPOL_REFERENCIA_Componente ERCAJ_BANCO_CAJ_BANCO_CONPOL_REFERENCIA_Componente;
public void ERCAJ_BANCO_CAJ_BANCO_CONPOL_REFERENCIA_OnChange()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_CONPOL_REFERENCIA_OnFocus()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_CONPOL_REFERENCIA_OnBlur()
{
}
//Metodos y atributos de _ERCAJ_BANCO.CAJ_BANCO.SYSTTP_CODIGO_K
public ERCAJ_BANCO_CAJ_BANCO_SYSTTP_CODIGO_K_Componente ERCAJ_BANCO_CAJ_BANCO_SYSTTP_CODIGO_K_Componente;
public void ERCAJ_BANCO_CAJ_BANCO_SYSTTP_CODIGO_K_OnChange()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_SYSTTP_CODIGO_K_OnFocus()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_SYSTTP_CODIGO_K_OnBlur()
{
}
//Metodos y atributos de _ERCAJ_BANCO.CAJ_BANCO.SYSTTS_CODIGO_K
public ERCAJ_BANCO_CAJ_BANCO_SYSTTS_CODIGO_K_Componente ERCAJ_BANCO_CAJ_BANCO_SYSTTS_CODIGO_K_Componente;
public void ERCAJ_BANCO_CAJ_BANCO_SYSTTS_CODIGO_K_OnChange()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_SYSTTS_CODIGO_K_OnFocus()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_SYSTTS_CODIGO_K_OnBlur()
{
}
//Metodos y atributos de _ERCAJ_BANCO.CAJ_BANCO.S_FI
public ERCAJ_BANCO_CAJ_BANCO_S_FI_Componente ERCAJ_BANCO_CAJ_BANCO_S_FI_Componente;
public void ERCAJ_BANCO_CAJ_BANCO_S_FI_OnChange()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_S_FI_OnFocus()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_S_FI_OnBlur()
{
}
//Metodos y atributos de _ERCAJ_BANCO.CAJ_BANCO.S_GUID
public ERCAJ_BANCO_CAJ_BANCO_S_GUID_Componente ERCAJ_BANCO_CAJ_BANCO_S_GUID_Componente;
public void ERCAJ_BANCO_CAJ_BANCO_S_GUID_OnChange()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_S_GUID_OnFocus()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_S_GUID_OnBlur()
{
}
//Metodos y atributos de _ERCAJ_BANCO.CAJ_BANCO.S_GUIDLOG
public ERCAJ_BANCO_CAJ_BANCO_S_GUIDLOG_Componente ERCAJ_BANCO_CAJ_BANCO_S_GUIDLOG_Componente;
public void ERCAJ_BANCO_CAJ_BANCO_S_GUIDLOG_OnChange()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_S_GUIDLOG_OnFocus()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_S_GUIDLOG_OnBlur()
{
}
//Metodos y atributos de _ERCAJ_BANCO.CAJ_BANCO.S_USUARIO
public ERCAJ_BANCO_CAJ_BANCO_S_USUARIO_Componente ERCAJ_BANCO_CAJ_BANCO_S_USUARIO_Componente;
public void ERCAJ_BANCO_CAJ_BANCO_S_USUARIO_OnChange()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_S_USUARIO_OnFocus()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_S_USUARIO_OnBlur()
{
}
//Metodos y atributos de _ERCAJ_BANCO.CAJ_BANCO.S_USUARIODB
public ERCAJ_BANCO_CAJ_BANCO_S_USUARIODB_Componente ERCAJ_BANCO_CAJ_BANCO_S_USUARIODB_Componente;
public void ERCAJ_BANCO_CAJ_BANCO_S_USUARIODB_OnChange()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_S_USUARIODB_OnFocus()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_S_USUARIODB_OnBlur()
{
}
//Metodos y atributos de _ERCAJ_BANCO.CAJ_BANCO.S_USUARIONOT
public ERCAJ_BANCO_CAJ_BANCO_S_USUARIONOT_Componente ERCAJ_BANCO_CAJ_BANCO_S_USUARIONOT_Componente;
public void ERCAJ_BANCO_CAJ_BANCO_S_USUARIONOT_OnChange()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_S_USUARIONOT_OnFocus()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_S_USUARIONOT_OnBlur()
{
}
//Metodos y atributos de _ERCAJ_BANCO.CAJ_BANCO.S_GUIDNOT
public ERCAJ_BANCO_CAJ_BANCO_S_GUIDNOT_Componente ERCAJ_BANCO_CAJ_BANCO_S_GUIDNOT_Componente;
public void ERCAJ_BANCO_CAJ_BANCO_S_GUIDNOT_OnChange()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_S_GUIDNOT_OnFocus()
{
}
public void ERCAJ_BANCO_CAJ_BANCO_S_GUIDNOT_OnBlur()
{
}

public ERCAJ_BANCO_Funciones()
{

    ERCAJ_BANCO_CAJ_BANCO_SYSUDN_CODIGO_K_Componente = ERCAJ_BANCO_CAJ_BANCO_SYSUDN_CODIGO_K_Componente.GetInstance();

    ERCAJ_BANCO_CAJ_BANCO_SYSTRA_CODIGO_K_Componente = ERCAJ_BANCO_CAJ_BANCO_SYSTRA_CODIGO_K_Componente.GetInstance();

    ERCAJ_BANCO_CAJ_BANCO_CAJBAN_SERIE_K_Componente = ERCAJ_BANCO_CAJ_BANCO_CAJBAN_SERIE_K_Componente.GetInstance();

    ERCAJ_BANCO_CAJ_BANCO_CAJBAN_REFERENCIA_Componente = ERCAJ_BANCO_CAJ_BANCO_CAJBAN_REFERENCIA_Componente.GetInstance();

    ERCAJ_BANCO_CAJ_BANCO_CAJBAN_BANCOREF_Componente = ERCAJ_BANCO_CAJ_BANCO_CAJBAN_BANCOREF_Componente.GetInstance();

    ERCAJ_BANCO_CAJ_BANCO_CONPOL_REFERENCIA_Componente = ERCAJ_BANCO_CAJ_BANCO_CONPOL_REFERENCIA_Componente.GetInstance();

    ERCAJ_BANCO_CAJ_BANCO_SYSTTP_CODIGO_K_Componente = ERCAJ_BANCO_CAJ_BANCO_SYSTTP_CODIGO_K_Componente.GetInstance();

    ERCAJ_BANCO_CAJ_BANCO_SYSTTS_CODIGO_K_Componente = ERCAJ_BANCO_CAJ_BANCO_SYSTTS_CODIGO_K_Componente.GetInstance();

    ERCAJ_BANCO_CAJ_BANCO_S_FI_Componente = ERCAJ_BANCO_CAJ_BANCO_S_FI_Componente.GetInstance();

    ERCAJ_BANCO_CAJ_BANCO_S_GUID_Componente = ERCAJ_BANCO_CAJ_BANCO_S_GUID_Componente.GetInstance();

    ERCAJ_BANCO_CAJ_BANCO_S_GUIDLOG_Componente = ERCAJ_BANCO_CAJ_BANCO_S_GUIDLOG_Componente.GetInstance();

    ERCAJ_BANCO_CAJ_BANCO_S_USUARIO_Componente = ERCAJ_BANCO_CAJ_BANCO_S_USUARIO_Componente.GetInstance();

    ERCAJ_BANCO_CAJ_BANCO_S_USUARIODB_Componente = ERCAJ_BANCO_CAJ_BANCO_S_USUARIODB_Componente.GetInstance();

    ERCAJ_BANCO_CAJ_BANCO_S_USUARIONOT_Componente = ERCAJ_BANCO_CAJ_BANCO_S_USUARIONOT_Componente.GetInstance();

    ERCAJ_BANCO_CAJ_BANCO_S_GUIDNOT_Componente = ERCAJ_BANCO_CAJ_BANCO_S_GUIDNOT_Componente.GetInstance();

}

	}
}

